# Deverá ser rodado do servidor de monitoramento
---
- hosts: server1
  gather_facts: no

  tasks:
    - name: Wait for connection to server1
      ansible.builtin.wait_for_connection:
        timeout: 30

- hosts: server2
  gather_facts: no

  tasks:
    - name: Wait for connection to server2
      ansible.builtin.wait_for_connection:
        timeout: 30
